config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create', as: :tasks

  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <% if @task.id %>
      <%= f.label :completed %>
      <%= f.check_box :completed %>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "tasks/form", task: @task %>

<p><%= link_to "Back to list", tasks_path %></p>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%  if task.completed? %>
        <i class="fas fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>
    <%= link_to task.title, task_path(task)%></li>
  <% end %>
</ul>
<br>
<p><%= link_to 'Add a new task', new_task_path %></p>

app/views/tasks/new.html.erb
<%= render "tasks/form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= link_to "Edit Task", edit_task_path %></p>
  <% if @task.completed %>
    <p>☑︎ This task is completed</p>
  <% else %>
    <p>☐  This task is not completed yet</p>
  <% end %>
<%= link_to "Delete", task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<br>
<p> <%= link_to 'Back to list',  tasks_path%></p>